### ISSUE TITLE
Location of Pfam-31_names_mod and DPD data

### ISSUE THREAD

**Issue by TimothyStephens** [functional-dark-side/agnostos-wf#1]
Hi,

First, thank you for developing such a comprehensive workflow.

I was setting up the workflow and was unable to find the Pfam-31_names_mod_01122019.tsv and DPD datasets required.
According to the config/config.yaml file the Pfam-31_names_mod_01122019.tsv file should be on Figshare but I am unable to find it using the links available through the pre-print. 
It also looks like the DPD website (http://darkproteome.ws/) is no long available (unless they have changed to a new site). Is there an alternative location to download the required DPD data? 

Hopefully I haven't completely overlooked these files somewhere obvious.

Thanks,
Tim.

**Comment by genomewalker** [comment]
Hey Tim
thank you very much for pointing us to this. You can get the files missing from [here](http://files.metagenomics.eu/agnostos-wf/databases.tar.gz) 
@ChiaraVanni: Can you check that all the data is available in Figshare?

Regarding the DPD data, we compiled the sequences from [here](https://www.pnas.org/content/112/52/15898). We tried to get the sequences from the [new version](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6630768/), but we never got an answer from the authors.
What a coincidence, I recently read [this](https://www.nature.com/articles/s41598-018-35620-z) because we are in the process of expanding our approach to Eukaryotes. If you are planning to use it for Eukaryotic data, let me warn you that at the moment we are getting some weird results and we still haven't figure out the cause.

Antonio

**Comment by TimothyStephens** [comment]
Hi Antonio,

Thank you for the quick reply and for linking to the missing datasets. 

Yes, I was planning on applying it to Eukaryotes using the data from [EukProt](https://www.biorxiv.org/content/10.1101/2020.06.30.180687v1) plus some other species our lab is interested in. 
I will keep what you said in mind when analyzing my results. Are the problems you encountered from the clustering stage or from a different step in the workflow? 

Thanks,
Tim.

**Comment by genomewalker** [comment]
Hi
we believe we need to do some calibrations to the downstream steps when assigning the clusters to known and unknown space. We were screening some metatranscriptomes and we found cases where clusters were classified as unknown but they should be known.  Now we are using EukProt to calibrate and understand what is going on, sometimes environmental sequences are tricky. Any insights and feedback is always welcome as our expertise in Eukaryotes is limited :-)

**Comment by ChiaraVanni** [comment]
Hi Tim,
thanks for the feedback. 
I have updated the Figshare data (adding the Pfam file and the DPD database) and the [download_DBs.sh](https://github.com/functional-dark-side/agnostos-wf/blob/master/download_DBs.sh) script.

**Comment by TimothyStephens** [comment]
Thank you @ChiaraVanni and @genomewalker for the information and updated databases, I will keep this in mind when analyzing my results. 

I will let you know if I see anything that might help with calibrating the workflow for Eukaryotes :)

Thanks,
Tim.
