### ISSUE TITLE
gcc error during installation 

### ISSUE THREAD

**Issue by mmcardozo** [functional-dark-side/agnostos-wf#19]
Dear all,

I keep having this error after running `sh installation_script.sh`Do you have any ideas how can I work around this? I checked on the path and the file does exits. The operative system is CentOS and the batch system SLURM.

Many thanks in advanced!

Magda
[error.txt](https://github.com/functional-dark-side/agnostos-wf/files/8901920/error.txt)

**Comment by ChiaraVanni** [comment]
Hi Magda,

first, it seems that it fails to connect to the OD-Seq download website:
`http://www.bioinf.ucd.ie/download/od-seq.tar.gz
Connecting to www.bioinf.ucd.ie (www.bioinf.ucd.ie)|137.43.93.206|:80... failed: Connection timed out.
Giving up.`

You can download od-seq.tar.gz from here for now: 
`wget https://figshare.com/ndownloader/files/35904569 -O od-seq.tar.gz`
and comment the line `wget http://www.bioinf.ucd.ie/download/od-seq.tar.gz` in the installation script.

For the other errors, I think you are missing openmpi (to run programs in MPI-mode)  and it seems that  your cmake needs to be updated.

Also, you are not writing in the `programs/` folder somehow and that's what is causing the final gcc errors, it cannot find the scripts because you are not in `agnostos-wf/` anymore.

Let me know if this is any help and if the installation runs correctly now.

Chiara

**Comment by mmcardozo** [comment]
Hi Chiara,

Following your suggestions and loading previously the cmake/3.22.0 and openmpi/4.0.2_intel17 as modules seem to fix some errors but the gcc error persist. Libraries seem to be installed ok. I Don't know why it says leaving the /agnostos-wf/ I am calling the script from that location. 
[error2.txt](https://github.com/functional-dark-side/agnostos-wf/files/8916993/error2.txt)

**Comment by ChiaraVanni** [comment]
Hi Magda,
seems that you are skipping this step:
https://github.com/functional-dark-side/agnostos-wf/blob/6fdc35803d88125da077197a375624755d5a59ba/installation_script.sh#L17
Can you check that this folder is being created?

**Comment by mmcardozo** [comment]
yes the folder is created and is empty

**Comment by ChiaraVanni** [comment]
yes, it looks like it worked :)

**Comment by mmcardozo** [comment]
Many thanks!

**Comment by mgabriell1** [comment]
Hi,
I just found this error as well. Other than loading `gcc` and `openmpi` I found that the cause of the issue was the comment on line 28 (https://github.com/functional-dark-side/agnostos-wf/blob/b11bd3b8d537045790e6a3af591c20d9ec3b0532/installation_script.sh#L28).
Since that file was not downloaded, it was not possible to extract it and move in its directory. This caused the `cd ..` on line 32 (https://github.com/functional-dark-side/agnostos-wf/blob/90e0ca00d7b2882fbcd48df1ad10ef4c68fa9a59/installation_script.sh#L32) to go back to the initial folder and not in `programs` resulting in this directory being empty.
I hope this might be helpful!

Marco
