### ISSUE TITLE
Conda env

### ISSUE THREAD

**Issue by AllanSSX** [functional-dark-side/agnostos-wf#2]
Hi,

I'm wondering why some dependencies are not included in the yaml file and need to be manually installed. I've take a look on Anaconda and they all seems available:

````bash
  - igraph
  - parasail-python
  - hmmer
  - ffindex
  - hhsuite
  - famsa
  - bioconductor-odseq
  - mmseqs2
````

Is there any reason to not put them into the yaml?

Thanks for your awesome workflow :)

**Comment by genomewalker** [comment]
Hi @AllanSSX 
thank you for using the workflow :-)

HMMER, HHSUITE, FFINDEX and MMSEQS2 are compiled with the MPI flags, and I don't think they are available in any of the conda channels as it is very system-specific.

We never tried the libs from igraph installed from conda to compile some of our programs, we will look at it.

We are using a modified version of the parasail-aligner app that uses similarities instead of identities to build the SSNs. We just updated the installation script, this was missing. Thanks!

And bioconductor-odseq is a reimplementation of the original algorithm in R. We are using the original OD-SEQ program in our workflow.

Thanks!

Antonio

**Comment by AllanSSX** [comment]
Hi Antonio,

Thanks for the fast reply!

Is there any particular reason to use the MPI version instead of the "standard" version?

I looked at the snakemake files and as our computer grid running under PBS pro, I will need to make some modifications in the code. Do you think I can remove the MPI flag without any troubles?

Best,
Alexandre

**Comment by genomewalker** [comment]
We designed the workflow to work with massive datasets in mind (hundreds of millions of genes). We use the ffindex and mmseqs2 apply functions extensively in the workflow to process the millions of clusters. I believe that it will take you forever to get the results using the non-MPI versions depending on the size of your dataset. In theory, it should be quite painless to use the workflow on PBS. You might want to modify the [cluster.yaml](https://github.com/functional-dark-side/agnostos-wf/blob/master/db_creation/config/cluster.yaml) to adapt it to your system and the `mpi-runner` in the [config.yaml](https://github.com/functional-dark-side/agnostos-wf/blob/master/db_creation/config/config.yaml#L41) to adapt to the MPI used in your HPC. Then you should modify: 
```
--cluster "sbatch --export=ALL -t {cluster.time} -c {threads} --ntasks-per-node {cluster.ntasks_per_node} --nodes {cluster.nodes} --cpus-per-task {cluster.cpus_per_task} --job-name {rulename}.{jobid} --partition {cluster.partition}"
```
in the Snakemake call to adapt it to your system. Unfortunately we don't have access to a PBS cluster to help you :-(

**Comment by AllanSSX** [comment]
I saw after creating a conda environment with all the dependencies that some of them seem to be able to run in MPI mode, but not all :/

I've just question: why using srun instead of sbatch for your mpi_runner?

**Comment by genomewalker** [comment]
The `mpi-runner` is for [MMSEQS2](https://github.com/soedinglab/MMseqs2/wiki#how-to-run-mmseqs2-on-multiple-servers-using-mpi). Maybe you will need to use `mpirun` instead of `srun` as we do, this is very system-specific. The difference between using `sbatch` and `srun` is that `sbatch` allocates the resources for the job. This is what we use for the `--cluster` in the snakemake call. Then `srun` inherits the options of `sbatch` and handles the communication between the MPI library and Slurm. It creates the MPI processes and distributes them to the allocated resources. I hope this helps.

**Comment by AllanSSX** [comment]
Yes, many thanks for the help!
